#Docker File for node js js application
FROM node:18-alpine

#working directory of our application
WORKDIR /usr/username/src/app

COPY package*.json ./

RUN npm install --silent

COPY .  .

EXPOSE 8082

CMD ["npm", "start"]